clientregister/urls.py
from django.contrib import admin
from django.urls import path,include
from social_django.urls import extra
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infofill.urls')),
    path('api/v1/',include('social_django.urls', namespace='social')),
    # path('api/v2/',include('social_django.urls', namespace='social')),
]

infofill/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

admin.site.site_header = 'DataFlow Client Management'
app_name = 'infofill'

urlpatterns = [
    path('home/login/via/google/', views.home, name='home'),
    #creater
    path('for/creator/1/', views.forcreator1, name='forcreator1'),
    # path('data/', views.forcreator2, name='forcreator2')
    path('form/', views.form, name='form'),
    path('logout_creator/', views.logout_creator, name='logout_creator'),
    path('go/live/<int:id>/', views.golive, name='golive'),
    path('completed/entry/', views.completed, name='completed'),
    #salesApprover
    # path('home2/login/via/google/', views.home2, name='home2'),
    path('sales/app/home/', views.salesapphome, name='salesapphome'),
    path('sales/app/action/', views.salesappaction, name='salesappaction'),
    path('logout_sales/app/', views.logout_salesapp, name='logout_salesapp'),
    path('approval/action/<int:id>/', views.approvalaction, name='approvalaction'),
    #ITApprover
    path('it/app/home/',views.itapphome, name='itapphome'),
    path('it/app/action/',views.itappaction, name='itappaction'),
    path('logout_it/app/',views.logout_itapp, name='logout_itapp'),
    path('est/date/<int:id>/', views.estdate, name='estdate'),
    path('after/close/', views.afterclose, name='afterclose'),
    path('est/date/given/', views.estdategiven, name='estdategiven'),
    #opsApprover
    path('ops/app/home/', views.opsapphome, name='opsapphome'),
    path('ops/app/action/', views.opsappaction, name='opsappaction'),
    path('logout_ops/app/', views.logout_opsapp, name='logout_opsapp'),
    path('uat/date/<int:id>/', views.uatdate, name='uatdate'),
    path('after/close/2/', views.afterclose2, name='afterclose2'),
    path('ops/date/given/', views.opsdategiven, name='opsdategiven'),
    ###creator action
    # path('action/home/', views.actionhome, name='actionhome'),
    # path('action/table/', views.actiontable, name='actiontable'),
    # path('logout_creator/action/', views.logout_creatoraction, name='logout_creatoraction'),

]

infofill/models.py
from django.db import models

class Fillup(models.Model):
    client_name = models.CharField(max_length=50, null=True, blank=True)
    client_type = models.CharField(choices=(('Existing Client Enhancement','Existing Client Enhancement'),('New Client Onboarding','New Client Onboarding')),max_length=50, default=None, null=True, blank=True)
    request_created_date = models.DateField(auto_now_add=True, editable=False)
    target_launch_date = models.DateField(null=True, default=None)
    request_synopsis = models.TextField(default='', null=True, blank=True)
    estimated_date = models.DateField(null=True, default=None, blank=True)
    actual_live_date = models.DateField(null=True, default=None, blank=True)
    current_status = models.CharField(max_length=100, blank=True, null=True)
    approval = models.CharField(choices=(('Pending','Pending'),('Approved','Approved'),('Reject','Reject')),max_length=20,default='Pending', blank=True)
    ontime_status = models.CharField(max_length=50, default='', null=True, blank=True)
    remarks = models.TextField(default='', null=True, blank=True)
    action = models.CharField(choices=(('Live','Live'),('Hold','Hold'),('Stop','Stop')),max_length=20, default='', blank=True,null=True)
    uat_date = models.DateField(null=True, default=None, blank=True)
    close = models.CharField(max_length=50, null=True, blank=True)
    close_2 = models.CharField(max_length=50, null=True, blank=True)



    def __str__(self):
        return '%s %s' %(self.client_name, self.approval)

class LoggedIn(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField()
    role = models.CharField(choices=(('Sales','Sales'),('Sales Approver','Sales Approver'),('IT Approver','IT Approver'),('OPS Approver','OPS Approver')),max_length=50)


    def __str__(self):
        return '%s %s' %(self.name, self.role)

class Link(models.Model):
    link = models.CharField(max_length=100)

    def __str__(self):
        return self.link

infofill/forms.py
from django import forms
from.models import Fillup

class FillupForm(forms.ModelForm):
    # client_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'enter client name'}))
    # request_synopsis = forms.Textarea(widget=forms.TextInput(attrs={'placeholder':'Enter'}))
    # contract_received_date = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control'}))
    # client_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'enter client name'}))
    # current_status= forms.CharField(widget=forms.D(attrs={'class':'bootstrap-select'}))

    class Meta:
        model = Fillup
        fields = [
            'client_type',
            'client_name',
            'request_synopsis',
            'target_launch_date',
        ]

        widgets = {
            'target_launch_date': forms.DateInput(attrs={'type': 'date'}),
            # 'current_status': forms.CharField(attrs={'class' : 'bootstrap-select'}),
        }


infofill/views.py
from django.shortcuts import render,redirect
from .forms import FillupForm
from django.contrib.auth import settings
from .models import Fillup, LoggedIn, Link
from django.contrib.auth import logout
from django.db.models import Q
from django.core.mail import send_mail
from django.utils import timezone
from datetime import datetime
import time

link = Link.objects.get(id=1).link


def home(request):
    settings.LOGIN_REDIRECT_URL = '/for/creator/1/'
    return render(request, 'infofill/home.html')

def forcreator1(request):
    data = Fillup.objects.all().exclude(action="Live").exclude(action='Stop').order_by('-id')
    for i in data:
        target_date = i.target_launch_date
        date_today = datetime.now().date()
        if target_date > date_today:
            i.ontime_status = 'On Time'
        else:
            i.ontime_status = 'Late'
    return render(request, 'infofill/forcreator.html', {'data': data})

def form(request):
    if request.method == 'POST':
        client_type = request.POST.get('clientSelect')
        active_clients = request.POST.get('activeclients')
        new_client = request.POST.get('newclient')
        textarea = request.POST.get('textarea')
        date = request.POST.get('date')

        if active_clients == '':
            obj = Fillup.objects.create(client_type=client_type, client_name=new_client, request_synopsis=textarea, target_launch_date=date)
            obj.save()
            salesapprover = LoggedIn.objects.filter(role='Sales Approver')
            # link = Link.objects.get(id=1).link
            send_mail(f'{new_client + " - " + textarea} - Request for approval',
                      f'login to give approval action: {link}/app/home/',
                      settings.EMAIL_HOST_USER, [i.email for i in salesapprover])  # give sales approver email
        else:
            obj = Fillup.objects.create(client_type=client_type, client_name=active_clients, request_synopsis=textarea, target_launch_date=date)
            obj.save()
            salesapprover = LoggedIn.objects.filter(role='Sales Approver')
            # link = Link.objects.get(id=1).link
            send_mail(f'{active_clients + " - " + textarea} - Request for approval',
                      f'login to give approval action: {link}/sales/app/home/',
                      settings.EMAIL_HOST_USER, [i.email for i in salesapprover])  # give sales approver email

        obj = Fillup.objects.order_by('-pk')[0]
        obj.current_status = 'Pending by Sales Approver'
        obj.save()
        return redirect('infofill:form')

    return render(request, 'infofill/form.html', {'form': form})
    #     form = FillupForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         client_name = request.POST.get('client_name')
    #         request_synopsis = request.POST.get('request_synopsis')
    #         obj = Fillup.objects.order_by('-pk')[0]
    #         obj.current_status = 'Pending by Sales Approver'
    #         obj.save()
    #         send_mail(f'{client_name +" - "+ request_synopsis}-Request for approval', 'login to give approval action: http://127.0.0.1:8000/sales/app/home/',
    #                   settings.EMAIL_HOST_USER, ['rsharma2@dataflowgroup.com', ])#give sales approver email
    #         return redirect('infofill:form')
    # form = FillupForm()
    # return render(request, 'infofill/form.html', {'form': form})

def logout_creator(request):
    logout(request)
    return redirect('infofill:home')

def golive(request, id):
    obj = Fillup.objects.get(pk=id)
    if request.method == 'POST':
        if '_live' in request.POST:
            Fillup.objects.filter(pk=id).update(action='Live')
            Fillup.objects.filter(pk=id).update(actual_live_date=timezone.now())

            return redirect('infofill:forcreator1')
        if '_hold' in request.POST:
            if obj.action == "Hold":
                Fillup.objects.filter(pk=id).update(action='')
                Fillup.objects.filter(pk=id).update(current_status='WIP')
                return redirect('infofill:forcreator1')
            else:
                Fillup.objects.filter(pk=id).update(current_status='Hold')
                Fillup.objects.filter(pk=id).update(action='Hold')
                return redirect('infofill:forcreator1')
        if '_stop' in request.POST:
            Fillup.objects.filter(pk=id).update(action='Stop')
            return redirect('infofill:forcreator1')


def completed(request):
    data = Fillup.objects.filter(Q(action='Live') | Q(action='Stop')).order_by('-id')
    for i in data:
        target_date = i.target_launch_date
        date_today = datetime.now().date()
        if target_date > date_today:
            i.ontime_status = 'On Time'
        else:
            i.ontime_status = 'Late'
    return render(request, 'infofill/completed.html', {'data':data})



#######

def salesapphome(request):
    # settings.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '582896860190-rntgt5tc2hsf3it77gn3f955771t6re6.apps.googleusercontent.com'
    # settings.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'qhIwKDYR5FVLSVDuWdDn2YoL'
    # settings.SOCIAL_AUTH__KEY = 'ID'
    # settings.SOCIAL_AUTH__SECRET = 'SECRET'
    settings.LOGIN_REDIRECT_URL = '/sales/app/action/'
    return render(request, 'infofill/home.html')

def salesappaction(request):
    data = Fillup.objects.filter(approval='Pending').exclude(client_name='').order_by('-id')
    action = Fillup.objects.filter(Q(approval='Approved') | Q(approval='Reject')).exclude(client_name='').order_by('-id')
    for i in data:
        target_date = i.target_launch_date
        date_today = datetime.now().date()
        if target_date > date_today:
            i.ontime_status = 'On Time'
        else:
            i.ontime_status = 'Late'
    return render(request, 'infofill/forsalesapp.html', {'data': data, 'action':action})

def logout_salesapp(request):
    logout(request)
    return redirect('infofill:salesapphome')

def approvalaction(request, id):
    if request.method == 'POST':
        if '_approve' in request.POST:
            obj = Fillup.objects.filter(pk=id).update(approval='Approved')
            obj = Fillup.objects.filter(pk=id).update(current_status='Pending By IT Approver')
            remark = request.POST.get('_textarea')
            Fillup.objects.filter(pk=id).update(remarks=remark)
            info = Fillup.objects.get(pk=id)
            sales = LoggedIn.objects.filter(role='Sales')
            itapprover = LoggedIn.objects.filter(role='IT Approver')
            send_mail(f'{info.client_name +" - "+ info.request_synopsis} - Request for Estimated Date', f'login to give Estimated Date : {link}/it/app/home/',
                      settings.EMAIL_HOST_USER, [i.email for i in itapprover]) #give IT approver email
            send_mail(f'Notification: {info.client_name +" - " + info.request_synopsis} -  Approved', f'login : {link}/home/login/via/google/',
                      settings.EMAIL_HOST_USER, [i.email for i in sales]) # give creator email
            return redirect('infofill:salesappaction')
        elif '_reject' in request.POST:
            obj = Fillup.objects.filter(pk=id).update(approval='Reject')
            remark = request.POST.get('_textarea')
            Fillup.objects.filter(pk=id).update(remarks=remark)
            info = Fillup.objects.get(pk=id)
            sales = LoggedIn.objects.filter(role='Sales')
            send_mail(f'Notification: {info.client_name +" - " + info.request_synopsis} - Rejected!', f'kindly login to view: {link}/home/login/via/google/',
                      settings.EMAIL_HOST_USER, [i.email for i in sales])#creator email
            return redirect('infofill:salesappaction')

####
def itapphome(request):
    settings.LOGIN_REDIRECT_URL = '/it/app/action/'
    return render(request, 'infofill/home.html')
def itappaction(request):
    data = Fillup.objects.filter(approval='Approved').exclude(close='close').order_by('-id')
    for i in data:
        target_date = i.target_launch_date
        date_today = datetime.now().date()
        if target_date > date_today:
            i.ontime_status = 'On Time'
        else:
            i.ontime_status = 'Late'
    return render(request, 'infofill/foritapp.html', {'data': data})

def afterclose(request):
    data = Fillup.objects.filter(approval='Approved').exclude(close='close').order_by('-id')
    for i in data:
        target_date = i.target_launch_date
        date_today = datetime.now().date()
        if target_date > date_today:
            i.ontime_status = 'On Time'
        else:
            i.ontime_status = 'Late'
    return render(request, 'infofill/foritapp.html', {'data': data})


def logout_itapp(request):
    logout(request)
    return redirect('infofill:itapphome')

def estdate(request, id):
    if request.method == 'POST':
        date = request.POST.get('_date', None)

        if '_dateSubmit' in request.POST:
            obj = Fillup.objects.filter(pk=id).update(estimated_date=date)
            return redirect('infofill:itappaction')
        if '_close' in request.POST:
            Fillup.objects.filter(pk=id).update(close='close')
            obj = Fillup.objects.filter(pk=id).update(current_status='Pending By OPS Approver')
            info = Fillup.objects.get(pk=id)
            opsapprover = LoggedIn.objects.filter(role='OPS Approver')
            sales = LoggedIn.objects.filter(role='Sales')
            send_mail(f'{info.client_name + " - " + info.request_synopsis} - Provide UAT Date',
                      f'kindly login to give UAT date: {link}/ops/app/home/',
                      settings.EMAIL_HOST_USER, [i.email for i in opsapprover])  # mail of ops approver

infofill/templates/infofill/forcreator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Client List</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/8aa13c88ab.js"></script>

    <style>
        body{
            background: #fff;
        }

        .logo{
            border-bottom: 5px solid #e7692f;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            background: #fff;
            padding: 0.25em 1em;
            display: flex;
            justify-content: space-between;
            z-index: 9999;
        }

        .logo .img-logo{
            flex: 1;
        }

        .logo .navbar{
            flex: flex-end;
        }

        .logout-icon{
            padding-right: 0.5em;
        }

        .logo .navbar .nav .nav-items a{
            color: #e7692f;
            text-decoration: none;
            padding: .5rem;
            border-radius: 4px;
            border: 1px solid #e7692f;
            transition: background 0.3s ease-in-out;
            outline: none;
            appearance: none;
            font-size: .8rem;
        }

        .logo .navbar .nav .nav-items a:hover{
            background: #e7692f;
            color: #fff;

        }

       .logo .navbar .nav .nav-items:nth-child(1) a {
            color: #e7692f;
            border: none;
            background: none;
            margin-right: 1rem;
        }

        .logo .navbar .nav .nav-items:nth-child(1) a i{
            padding-right: 0.5rem;
        }

        .logo .navbar .nav .nav-items:nth-child(1) a:hover{
            color: #c55b2b;
        }

        .navigation{
            margin-top: 5rem;
            position: fixed;
            top: -8px;
            left: 0;
            width: 10%;
            height: 100%;
            background: #f0f0f0;
            border-right: 5px solid #e7692f;
        }

        .navigation ul{
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin-top: 2.5rem;
            margin-left: -2.5rem;
        }

        .navigation ul li{
            list-style-type: none;
            color: #000;
            transition: all 0.3s ease-in-out;
        }

        .navigation ul li:hover{
            background: #9e9e9e;
        }

        .navigation ul li:hover a{
            color: #fff !important;
        }

        .navigation ul li a{
            display: block;
            color: #000;
            font-size: 1rem;
            font-weight: 500;
            text-decoration: none;
            padding: 0.5rem 1rem;
            width: 100%;
            transition: all 0.3s ease-in-out;
        }

        .active{
            background: #e7692f;
            transition: all 0.3s ease-in-out;
        }

        .active{
            color: #fff !important;
        }

        .cont,
        .cont2{
            margin-top: 6rem;
            margin-bottom: 1rem;
            margin-left: 10%;
            display: grid;
            justify-content: center;
            align-items: center;
            width: 90%;
        }

        .cont2{
            display: none;
        }

        .client-details{
            border: 1px solid #5d5d5d;
            border-collapse: collapse;
            border-style: hidden;
            border-radius: 10px;
            width: 100%;
            table-layout: fixed;
            background: #fff;
        }

        .client-details thead{
            filter: drop-shadow(-1px 3px 3px rgba(0, 0, 0, 0.2));
        }

        .client-details th{
            padding: 1em;
        }

        .client-details td{
            padding: 0.5em 1em;
        }

        .client-details th{
            background: #5d5d5d;
            color: #fff;
        }

        .client-details tr:first-child th:first-child {
          border-top-left-radius: 10px;
        }

        .client-details tr:first-child th:last-child {
          border-top-right-radius: 10px;
        }

        .tb-content{
          height: calc(100vh - 12em);
          overflow-x:auto;
          width: 100%;
          border: 1px solid rgba(255,255,255,0.3);
          box-shadow: 0px 0px 4px rgba(0,0,0,0.2);
        }

        .tb-content tr{
            font-size: 0.8em;
        }

        .tb-content::-webkit-scrollbar-track{
            background-color: #ccc;
        }

        .tb-content::-webkit-scrollbar{
            width: 5px;
            background-color: #5d5d5d;

        }

        .tb-content::-webkit-scrollbar-thumb{
            background-color: #5d5d5d;
            border: 2px solid #3f3f3f;
            border-radius: 100px;
        }

        .tb-content .client-details tr{
            border-bottom: 1px solid #5d5d5d30;
        }

        .tb-content .client-details tr:nth-child(even){
            background: #f0f0f0;
        }

        .live-action .btn-action{
            background: none;
            border: none;
            border: 1px solid transparent;
            padding: .2em;
        }

        .live-action input{
            outline: none;
            appearance: none;
        }

        .live-action .fa-wifi:hover{
            color: green;
            border: 1px solid green;
            border-radius: 50%;
        }

        .live-action .fa-play:hover,
        .live-action .fa-pause-circle:hover{
            color: brown;
            border: 1px solid brown;
            border-radius: 50%;
        }

        .live-action .fa-ban:hover{
            color: tomato;
            border: 1px solid tomato;
            border-radius: 50%;
        }

    </style>

</head>
<body>

 <div class="logo">
     <div class="img-logo">
        <img src="https://s3-ap-southeast-1.amazonaws.com/dataflow-dfgcorp/wp-content/uploads/2017/01/16145628/logo_new.png" alt="logo" width= "60px" height="60px">
    </div>
     <nav class="navbar">
        <ul class="nav">
            <li class="nav-items">
                <a href="{% url 'infofill:form' %}"><i class="fas fa-plus add-btn"></i>Add new client</a>
            </li>
            <li class="nav-items">
                <a href="{% url 'infofill:logout_creator' %}"><i class="fas fa-power-off logout-icon"></i><strong>Logout</strong></a>
            </li>
        </ul>
    </nav>
 </div>

<div class="navigation">
    <ul>
        <li class="">
            <a href="{% url 'infofill:forcreator1' %}" class="tablinks active">Active</a>
        </li>
        <li>
            <a href="{% url 'infofill:completed' %}" class="tablinks">Completed</a>
        </li>
    </ul>
</div>




<div class="container-fluid cont tabcontent" id="Active">
    <div class="tb-header">

            <table class="client-details" cellpadding="4">
                <thead>
                    <tr>
                        <th>Cient name</th>
                        <th>Request Synopsis</th>
                        <th>Client Type</th>
                        <th>request receive date</th>
                        <th>Target launch date</th>
                        <th>Estimated Date</th>
                <!--        <th>Actual live date</th>-->
                        <th>UAT Date</th>
        <!--                <th>Ontime Status</th>-->
                        <th>Current status</th>
                        <th>Action</th>
                <!--        <th>Remarks</th>-->
                <!--        <th>Action by Sales Approver</th>-->
                <!--        <th>Action</th>-->
                <!--        <th>Select action</th>-->
                    </tr>
                </thead>
            </table>
    </div>

     <div class="tb-content">
            <table class="client-details" cellpadding="4">
                {% for i in data %}
                    <tr>
                        <td>{{i.client_name}}</td>
                        <td>{{i.request_synopsis}}</td>
                        <td>{{i.client_type}}</td>
                        <td>{{i.request_created_date}}</td>
                        <td>{{i.target_launch_date}}</td>
                        <td>{{i.estimated_date}}</td>
        <!--                <td>{{i.actual_live_date}}</td>-->
                        <td>{{i.uat_date}}</td>
<!--                        <td>{{i.ontime_status}}</td>-->
                        <td>{{i.current_status}}</td>
                        <td>
                            <form method="post" action="{% url 'infofill:golive' i.id %}" class="live-action">
                    {% csrf_token %}
                    {% if i.action == 'Live' or i.action == 'Stop' %}{% endif %}
                        {% if i.action == 'Hold' %}
                            <input type="submit" name="_live" value="&#xf1eb" class="fas fa-wifi btn-action">
                            <input type="submit" name="_hold" value="&#xf04b" class="fas fa-play btn-action">
                            <input type="submit" name="_stop" value="&#xf05e" class="fas fa-ban btn-action">
                        {% endif %}
                        {% if i.action == '' or i.action == None %}
                            <input type="submit" name="_live" value="&#xf1eb" class="fas fa-wifi btn-action">
                            <input type="submit" name="_hold" value="&#xf28b" class="fas fa-pause-circle btn-action">
                            <input type="submit" name="_stop" value="&#xf05e" class="fas fa-ban btn-action">
                         {% endif %}

                            </form>
                        </td>
        <!--                <td>{{i.remarks}}</td>-->
        <!--                <td>{{i.approval}}</td>-->
        <!--                <td>{{i.action}}</td>-->
        <!--                <td><a href="/admin/infofill/fillup/{{i.id}}/change/">action</a></td>-->
                    </tr>
                {% endfor %}
            </table>
        </div>

</div>

</body>
</html>

infofill/templates/infofill/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://kit.fontawesome.com/8aa13c88ab.js"></script>

    <title>Login</title>

    <style>
       @import url('https://fonts.googleapis.com/css?family=PT+Sans:400,700&display=swap');
        *{
            box-size: border-box;
            font-family: 'PT Sans', sans-serif;
        }

        html,
        body{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'PT Sans', sans-serif;
        }

        .front-form{
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .front-form .logo,
        .front-form .frame{
            flex: 1;
            width: 100%;
            height: 100vh;
        }

        .front-form .logo{
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .front-form .logo img{
            width: 200px;
            height: 200px;
            display: block;
            align-self: center;
        }

        .front-form .frame{
            background: #e7692f;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .login-card{
            border: 2px solid #fff;
            padding: 2em;
            border-radius: 10px;
            box-shadow: 0px 0px 4px rgba(0, 0, 0, 0.5);
        }

        .google-logo h1{
            color: #fff;
            width: 80%;
            font-size: 2em;
            padding-bottom: .5em;
            border-bottom: 2px solid #f79d5d;
        }

        .login-btn{
            background: #3294ff;
            color: #fff;
            padding: 0.5em  1em;
            border-radius: 10px;
            display: block;
            width: 50%;
            text-align: center;
            margin-top: 1rem;
            text-decoration: none;
        }

        a.login-btn i {
            margin-right: 1em;
        }

        a.login-btn:hover{
            background: #0056b3;
            color: #fff;
            text-decoration: none;
            transition: all 0.3s ease-in;
        }



    </style>
</head>
<body>

<section class="front-form">
    <div class="logo">
        <img src="https://lh3.googleusercontent.com/-ljyCnMuymvc/XT5yciHAwiI/AAAAAAAAAAI/uf4fKMhEpigaSvnzA62kiP52oRp0WU7QQCK8BGAs/s122/2019-07-28.png" alt="logo">
    </div>

    <div class="frame">
        <div class="parent">
            <div class="login-card">
                <div class="google-logo">
<!--                    <img src="https://cdn4.iconfinder.com/data/icons/new-google-logo-2015/400/new-google-favicon-512.png" alt="logo">-->
                    <h1><strong>Login With Google</strong></h1>
                </div>
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="login-btn"><i class="fab fa-google"></i>Login</a>
            </div>
        </div>
    </div>
</section>

</body>
</html>